### ISSUE TITLE
Personal todo

### ISSUE THREAD

**Issue by ZeroEkkusu** [ZeroEkkusu/aave_brownie_py#1]
- [ ] CHALLENGE: short selling
- [ ] Repaying remaining debt with collateral using flash loans
- [ ] Change the tests when done

**Comment by ZeroEkkusu** [comment]
Hints:
- [Swapping (py)](https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions/30#discussioncomment-1358216)
- Uniswap swapping [as a contract](https://docs.uniswap.org/protocol/V2/guides/smart-contract-integration/trading-from-a-smart-contract)
- [Aave flash loan docs](https://docs.aave.com/developers/guides/flash-loans)
- [The Paraswap adapter and flash loans contract](https://github.com/aave/protocol-v2/blob/b4ef5d88b2fac93b2dc844d050dfcade52d9de85/contracts/adapters/ParaSwapLiquiditySwapAdapter.sol)
